/* Generated by Racket Script! */

#pragma once

enum class SyntaxNodeType {
    Invalid = 0,

    ArrayExpression,
    ArrayPattern,
    ArrowFunctionExpression,
    AssignmentExpression,
    AssignmentPattern,
    AsyncArrowFunctionExpression,
    AsyncFunctionDeclaration,
    AsyncFunctionExpression,
    AwaitExpression,
    BinaryExpression,
    BlockStatement,
    BreakStatement,
    CallExpression,
    CatchClause,
    ClassBody,
    ClassDeclaration,
    ClassExpression,
    ComputedMemberExpression,
    ConditionalExpression,
    ContinueStatement,
    DebuggerStatement,
    Directive,
    DoWhileStatement,
    EmptyStatement,
    ExportAllDeclaration,
    ExportDefaultDeclaration,
    ExportNamedDeclaration,
    ExportSpecifier,
    ExpressionStatement,
    ForInStatement,
    ForOfStatement,
    ForStatement,
    FunctionDeclaration,
    FunctionExpression,
    Identifier,
    IfStatement,
    Import,
    ImportDeclaration,
    ImportDefaultSpecifier,
    ImportNamespaceSpecifier,
    ImportSpecifier,
    LabeledStatement,
    Literal,
    MetaProperty,
    MethodDefinition,
    Module,
    NewExpression,
    ObjectExpression,
    ObjectPattern,
    Property,
    RegexLiteral,
    RestElement,
    ReturnStatement,
    Script,
    SequenceExpression,
    SpreadElement,
    StaticMemberExpression,
    Super,
    SwitchCase,
    SwitchStatement,
    TaggedTemplateExpression,
    TemplateElement,
    ThisExpression,
    ThrowStatement,
    TryStatement,
    UnaryExpression,
    UpdateExpression,
    VariableDeclaration,
    VariableDeclarator,
    WhileStatement,
    WithStatement,
    YieldExpression,

};

class SyntaxNode;
class Expression;
class Statement;
class Pattern;
class Declaration;
class ArrayExpression;
class ArrayPattern;
class ArrowFunctionExpression;
class AssignmentExpression;
class AssignmentPattern;
class AsyncArrowFunctionExpression;
class AsyncFunctionDeclaration;
class AsyncFunctionExpression;
class AwaitExpression;
class BinaryExpression;
class BlockStatement;
class BreakStatement;
class CallExpression;
class CatchClause;
class ClassBody;
class ClassDeclaration;
class ClassExpression;
class ComputedMemberExpression;
class ConditionalExpression;
class ContinueStatement;
class DebuggerStatement;
class Directive;
class DoWhileStatement;
class EmptyStatement;
class ExportAllDeclaration;
class ExportDefaultDeclaration;
class ExportNamedDeclaration;
class ExportSpecifier;
class ExpressionStatement;
class ForInStatement;
class ForOfStatement;
class ForStatement;
class FunctionDeclaration;
class FunctionExpression;
class Identifier;
class IfStatement;
class Import;
class ImportDeclaration;
class ImportDefaultSpecifier;
class ImportNamespaceSpecifier;
class ImportSpecifier;
class LabeledStatement;
class Literal;
class MetaProperty;
class MethodDefinition;
class Module;
class NewExpression;
class ObjectExpression;
class ObjectPattern;
class Property;
class RegexLiteral;
class RestElement;
class ReturnStatement;
class Script;
class SequenceExpression;
class SpreadElement;
class StaticMemberExpression;
class Super;
class SwitchCase;
class SwitchStatement;
class TaggedTemplateExpression;
class TemplateElement;
class ThisExpression;
class ThrowStatement;
class TryStatement;
class UnaryExpression;
class UpdateExpression;
class VariableDeclaration;
class VariableDeclarator;
class WhileStatement;
class WithStatement;
class YieldExpression;

